### ISSUE TITLE
*.pyc files present in repository

### ISSUE THREAD

**Issue by bazylip** [HuiZeng/Grid-Anchor-based-Image-Cropping-Pytorch#5]
Cloning repository and trying to run `demo_eval.py` script causes it to crash due to `*.pyc` files present in `roi_align` directory. 
```
user@pc:~/Grid-Anchor-based-Image-Cropping-Pytorch$ python demo_eval.py 
Traceback (most recent call last):
  File "demo_eval.py", line 1, in <module>
    from croppingModel import build_crop_model
  File "~/Grid-Anchor-based-Image-Cropping-Pytorch/croppingModel.py", line 4, in <module>
    from roi_align.modules.roi_align import RoIAlignAvg, RoIAlign
ImportError: bad magic number in 'roi_align': b'\x03\xf3\r\n'
```

It can be easily fixed by removing these files e.g.
```
sudo find . -name "*.pyc" -exec rm -f {} \;
```

**Comment by HuiZeng** [comment]
Hi， thanks for your good suggestion.
